# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.10 on 2016-11-13 02:21
=======
# Generated by Django 1.9.10 on 2016-11-13 02:36
>>>>>>> 8e52d8c4f1a542727d89e5bf0151e078c26dc8ca
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='introduction',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
