# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='introduction',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
