# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='log_type',
            field=models.CharField(default='Market', max_length=100),
            preserve_default=False,
        ),
    ]
