# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tradelog_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='log_info',
            field=models.CharField(default={}, max_length=100),
            preserve_default=False,
        ),
    ]
