# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tradelog_log_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradelog',
            old_name='trade_time',
            new_name='log_time',
        ),
    ]
