# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symbols', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tradingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('real_time_index', models.BooleanField(default=True)),
                ('waitingtime', models.CharField(default='30', max_length=200)),
                ('trade_config_json', models.TextField(blank=True, null=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategies')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symbols.symbols')),
            ],
        ),
        migrations.AddField(
            model_name='tradelog',
            name='trade_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tradingTask'),
        ),
    ]
