# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='trade_type',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='trade_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.tradingTask'),
            preserve_default=False,
        ),
    ]
