# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradelog',
            old_name='alert_time',
            new_name='trade_time',
        ),
        migrations.AddField(
            model_name='tradingtask',
            name='real_time_index',
            field=models.BooleanField(default=True),
        ),
    ]
