# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20161105_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingtask',
            name='waitingtime',
            field=models.CharField(default='30', max_length=200),
        ),
    ]
